### ISSUE TITLE
Issue with logging into the UI

### ISSUE THREAD

**Issue by arbeiterz** [allegroai/clearml#102]
So, somehow, the password I used for my web server was overwritten in my keychain.  How do I forcefully reset my password?  I have trains running in a docker container.

**Comment by bmartinn** [comment]
Hi @arbeiterz,

I assume you're referring to the password you're using when logging into the Trains web-UI, is that correct?
This would mean you're using a fixed-user setup (as described [here](https://github.com/allegroai/trains-server/blob/master/docs/faq.md#can-i-add-web-login-authentication-to-trains-server-)), in which case the user/password information can be found in the `apiserver.conf` file, and you can easily find your password there.

Please let me know if that answers your question, if if I got it all wrong :)

**Comment by arbeiterz** [comment]
Hi @bmartinn ,

I've not logged into my trains instance in some time so I don't really recall how I was signing in.  When I look in /opt/trains/config, there's absolutely nothing in that directory.  However, when I look in /opt/trains/server/config/default, and then look at apiserver.conf, there's no specific users listed there.

Further more, on my client side, in trains.conf api section, there's some encrypted credentials there.

Can't recall now HOW I was access my trains instance.  Stinks, too, because I had a ton of training data there that I need to get at.  Thanks for your help so far.

**Comment by bmartinn** [comment]
Hi @arbeiterz,

First of all, don't worry - if the server is still there and the data folder was not deleted, you can still get to your experiments. We designed _Trains_ so that it'll be easy to deploy and use locally for use by a team, where you normally care more about ease of access than protecting your experiments from your team members, which means that even if you log in as another user, you can still see and use your old experiments :)

If you haven't configured any fixed-users, than your Web-UI login shouldn't request a password at all - you're just required to enter a name, which will be shown alongside your experiments. It should look similar to our demo server login:
![image attached](https://user-images.githubusercontent.com/51887611/74098913-3cda4780-4b26-11ea-9227-f4387780bc69.png)

When you click on the "Full Name" field and start typing, the Web-UI will try to auto-complete, so you can easily find out what name you used last time you logged into the system. As I've mentioned before, you can also just login with a new name :)

What you see in the client side in your `trains.conf` file, are your server-generated credentials (which you probably pasted there when running the `trains-init` configuration wizard) - these are used by _Trains_ (and _Trains-Agent_) to communicate with the server when running experiments, and you can absolutely keep them as is, there's no need to configure them again or generated new ones, even if you're using a new name to log into the Web-UI.

Thanks for using _Trains_! - we're here to help :)
