### ISSUE TITLE
Saving source code as artifact

### ISSUE THREAD

**Issue by kwanUm** [allegroai/clearml#103]
I'm successfully able to run the trains-server on my linux machine, and now running a task (through Slurm) that connects to this server and report results. 

ATM, I'm looking for TRAINS to only log relevant artifacts for me - such as my source code for starters. Is there a way to configure TRAINS to save a set of files that conform to a regex for that purpose? "sending_source" flag doesn't seem to exist anymore.

**Comment by kwanUm** [comment]
Following up on this with more info on my env.

I'm developing locally on my macbook and connecting to a cluster to run my experiments. I'm using PyCharm to sync my code between my environment on the laptop, to the one on the cluster.
To run training on the cluster, I'm connecting to a fixed machine on it through SSH, and from there using SLURM to allocate resources for my training. All of the machines on the cluster share the same file system through NFS, so they all get visibility to my code and conda environment.

If I'd like to log my code in this configuration, I can either:
- Sync the .git/ folder through PyCharm to the remote cluster - seems like this folder is 4GB in my case, and I'm not sure whether PyCharm will be able to auto-sync it whenever I change files...
- Log all of the **/*.py files manually with Task.add_artifact. 
Am I missing any other alternative, and is there an example for how to do the above that you can share?

Thanks!

**Comment by bmartinn** [comment]
Hi @kwanUm ,
Regrading the first question, yes you package all the python files into a single zip file, and upload it as an artifact using the following line: 
```python
task.upload_artifact('code', './*.py')
```
Do notice that it will always **recursively** look for all the matching (wildcard) files (basically rglob).

As for adding `.git` in the pycharm sync, I guess it is the easiest solution in your specific setup, as it will make sure that when running the code with the SLURM scheduler the correct code base is referenced (since there is a .git folder present).
In order to remove the `.git` from the pycharm exclude list, go to:
Settings -> Build, Execution, Deployment -> Deployment -> Options,
And remove ".git": from the "Exclude items by name" list.
See full discussion [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000505230-Syncing-git-directory)

**Comment by kwanUm** [comment]
Thanks for the prompt reply Martin.

I'll go ahead and attempt the second approach (sync .git/ folder) and
report back. It's a bit large in my case (4GB) but re-syncing it should be
fairly small.

I'm not sure I fully understood you by "make sure that when running the
code with the SLURM scheduler the correct code base is referenced".
My cluster is managed with SLURM where all servers have access to the same
file system (NFS), so AFAIK my SLURM running tasks don't look at the .git/
folder at all.
Have you  perhaps meant to refer to some integration of TRAINS with SLURM?

**Comment by bmartinn** [comment]
Hey @kwanUm , my apologies, it was a bit enigmatic.

What I meant was that when SLURM executes a *trains* code  (i.e. execution not using the *trains-agent*), you still want to log the git repository (or in other words, reference the git repository).
The Git repository will automatically be logged if a .git folder exists in execution time. Considering your setup, it should not be a problem, as this is a shared NFS folder, which you synced your .git folder with, and since the SLURM execution uses that same NFS folder.

That said, I can see how fragile this setup is... Image switching to a different branch, while you have a job executed on the SLURM cluster using the same repository folder...

I would recommend creating a glue layer between *Trains* and SLURM.
Like a service popping experiments from the *Trains* queue and pushing them into the SLURM scheduler.

**Comment by smao-astro** [comment]
Hi @kwanUm ,

Though now it is more than one year past since you open the issue, but I am still curious to know if you have found that best solution to the problem since I am almost facing the same issue:

1. I am using SLURM (mandatory) on a HPC.
2. I update code recursively very fast, that means, I might submit a slurm job with git commit `1`, and continue update my model to git commit `2` while waiting the job with `1` actually begins. So I do want to save a snapshot of the code to have the slurm jobs run using my code version at the time of submit a job instead of the latest version at the time of job begin.
3. I want to know how to use ClearML-agent to manage tasks.
    1. Because of 1, seems that I do not want to use queue, instead use `agent execute`. (correct me if I am wrong, but since resource is managed by SLURM, I do not know why I need queue)
    2. I want to use [task SDK python API](https://clear.ml/docs/latest/docs/guides/automation/task_piping) to clone a template task and rerun with different hyperparameters.
    2. Because of 2, I am looking into how `agent execute` would make a copy of my source code.

Seems still a mess, but I can imagine the workflow should like:
```
start `clearml-agent execute` on login node (**code snapshotted**)-> slurm job start -> Task.clone and run on compute node
```
The part "code snapshotted" is where I do not know how to.

Would you like to share some experience?
Thanks.

**Comment by bmartinn** [comment]
Hi @smao-astro 
> 3.i. Because of 1 ...

That makes total sense, use SLURM for resource allocation and the agent for the environment setup and control over the parameters passed.

> 3.ii. I want to use task SDK python API to clone a template task and rerun with different hyperparameters

Sure this will work, including changing hyper parameters, the agent will take care of transparently passing them into the process, so nothing to worry about here. The only thing that is missing is that there will not be any automation of the launch (i.e. you will have to "manually" launch the SLURM job via the sbatch/srun command)

> 3.iii Because of 2, I am looking into how agent execute would make a copy of my source code. ...

Let's assume we want to launch Task ID `aabbcc` then the slurm job to run would be something like:
`clearml-agent execute --id aabbcc`

Which would create a new venv environment on any node, clone the code, apply any uncommitted changes, and run the Task including hyper parameters.

wdyt?
