### ISSUE TITLE
Load an "untracked" config file

### ISSUE THREAD

**Issue by jblereste** [allegroai/clearml#113]
Hi Allegro AI team,

I think that currently I can't do this but I want to know if you plan to handle it or if you have a cool solution for me.

Locally, I can run this command:
```bash
$ python ./my_script.py --configuration_file=config_1.json
```
It works and I can see the results on the web UI.
I can visualize all the hyper-parameters thanks to the task.connect() function.

Now, I want to do a script that take a list of config files, and for each config file, clone the task previously created, set the configuration_file and enqueue it (one task for each configuration file).

I don't need and want to commit the config files (I can see the hyper-parameters used thanks to the web UI).

Is there a way to use task.enqueue with untracked file?

Thank you,
Jean-Baptiste

**Comment by bmartinn** [comment]
Hi @jblereste , I might have a solution for you:
Are you aware of `Task.connect_configuration` ([doc](https://allegro.ai/docs/task.html?highlight=task%20init#trains.task.Task.connect_configuration)) ?

Basically what `Task.connect_configuration` does when given a link to a file, is storing the content of that file inside the experiment.
So if you do:
```python
config_file = task.connect_configuration('config_1.json')
model_config_dict = json.load(open(config_file, 'rt'))
```
When the *trains-agent* is executing the experiment, instead of storing the content of "config_1.json" in the experiment , it will take the content of the configuration from the experiment create a local temporary file dump the content into the file and return it as "config_file" (for example `model_config_dict` will be "/tmp/temp_config.json")

You can find an example code [here](https://github.com/allegroai/trains/blob/master/examples/manual_model_config.py#L17)

Now in order to automate the process, you can do something similar to the [automl example](https://github.com/allegroai/trains/blob/master/examples/automl/automl_random_search_example.py#L30), you can do:
```python
config_text = open('config_2.json', 'rt').read()
cloned_task.set_model_config(config_text=config_text)
```

What do you think?
