### ISSUE TITLE
How to update pipeline steps created with add_function_step?

### ISSUE THREAD

**Issue by kiranzo** [allegroai/clearml#1338]
Not sure if this is really a bug, or I'm doing something wrong.

## Describe the bug / To reproduce

I inherited some ClearML pipelines from the previous dev. I made some changes to pipeline step (saving artifact in parquet instead of csv and a parameter that lets you choose which), that required to change both code of the step and code of the controlling pipeline, then I committed them to a test branch on Git. 
I cloned the existing pipeline in ClearML Web UI and tried to change source branch in the pipeline parameters, but it didn't affect behaviour of the pipeline step.
I tried to go to 'configuration objects' menu and change the branch for that particular step, but it seems it ignored Git commit and just took the code from the 'uncommitted changes' in the step configuration.
![image](https://github.com/user-attachments/assets/18e51dc2-ee4c-4d28-8ab8-409b634e4408)

I tried to clone my pipeline again and clear configuration object for that step altogether, or just set "diff" to null, but in both cases, I got this error message: 
`/usr/bin/python3: can't open file '/root/.clearml/venvs-builds/task_repository/pipelines.git/create_clearml_dataset.py': [Errno 2] No such file or directory`
It seems it just can't generate new code from the function when there's no `diff`.

## Expected behaviour
Was I supposed to use `Pipeline.run()` and create everything completely anew instead of cloning (I'm not sure I can do that easily, given that pipeline is supposed to run in speacially prepared Docker container)? It's really counterintuitive what we should do when pipeline steps are created from functions. What's the easiest way to modify the code of the pipeline step (easiest = best for lazy researchers)?

## Environment
* Server type - self hosted
* ClearML SDK Version - 1.16.3
* ClearML Server Version - 1.14.1
* ClearML Agent Version - 1.8.1
* Python Version - 3.8
* OS - Linux

**Comment by eugen-ajechiloae-clearml** [comment]
Hi @kiranzo ! In your case, I think it would be easier to run everything programatically instead of changing the parameters in the UI.
`I'm not sure I can do that easily, given that pipeline is supposed to run in speacially prepared Docker container` You can actually set the Docker image you want your steps to run in using the `docker` parameter in `add_function_step`. And even when cloning, the step itself would need to be re-ran in some environment, so this can't really be avoided.
Note that, in order to use the Docker image, you need to run the pipeline via an agent (so basically a remote run). The agent can run locally on your machine tho, as long as you have access to the docker image you are trying to pull. Note that the agent needs to run in docker mode, so pass the `--docker` flag to `clearml-agent` e.g. `clearml-agent daemon --queue default --docker` 
Also, pipeline steps can be cached using `cache_executed_step=True` in `add_function_step`. Using this, you can experiment faster, as cached steps will not be re-ran (unless they are modified, in which case the cache is invalidated).

**Comment by kiranzo** [comment]
Thanks for the answer, @eugen-ajechiloae-clearml

I was meaning to ask another thing, and since you are here...

Since we've started using ClearML, we've received a lot of complaints about web interface, mostly related to pipelines, it could really use some UX engineering (for example, asking to set both execution queue and default queue for pipeline steps when enqueuing pipeline - that would improve usability a lot).
We're low-key discussing gathering UX requirements from our researchers, and then asking a front end dev to modify Web UI for us. However, some of us are concerned that we'll have to support new branch of Web UI ourselves and modify it with each new version of ClearML server.

So, my question is, what does ClearML team think of accepting a pull request with some web UI improvements?

**Comment by ainoam** [comment]
@kiranzo we always welcome contributions - Thanks for considering this!!
For the UI, it would be most productive to discuss your suggestions at the clearml-web [repo](https://github.com/allegroai/clearml-web/), to make sure they (and their implementation) are aligned with the direction ClearML is going.
