### ISSUE TITLE
Unable to view logged debug images

### ISSUE THREAD

**Issue by majdzr** [allegroai/clearml#176]
Hello, 
Thanks again for the awesome product!

I have an issue with logging and viewing debug images. I'm trying to log an image with `logger.report_image()`. However, in the UI, I get "Unable to load image" window. If I copy the URL of the image from the UI, I get something like: http://_serverip_:8081/_projectname_/_taskname_/metrics/_xyz_.jpeg.
If I click Open Image, I get, rightfully, that the path doesn't exist. If I go to the same path on the server AWS instance, and I add _/opt/trains/data/fileserver/_ to it, I find all the images nicely saved. 
Any ideas what's going on?
I have already checked that the project and task names don't have special characters. 

Thank you in advance.

**Comment by jkhenning** [comment]
Hi @majdzr ,

Thanks for your kind words 😄 

This sounds like it might be caused by a CORS issue... Can you try and see the Developer's Console Network tab and check if there's any console error or what's the response when trying to load this image using `http://serverip:8081/projectname/taskname/metrics/xyz.jpeg`?

Also, a good test can be a simple cURL command from the server's console (I assume you can SSH to it), something like:
`curl http://localhost:8081/projectname/taskname/metrics/xyz.jpeg -o file.jpeg`

And see what happens...

**Comment by majdzr** [comment]
Hello,

> Can you try and see the Developer's Console Network tab and check if there's any console error or what's the response when trying to load this image using http://serverip:8081/projectname/taskname/metrics/xyz.jpeg?

I get this from the console when trying to load the image:

_Failed to load resource: net::ERR_CONNECTION_TIMED_OUT_

but also a warning (probably unrelated): 
_DevTools failed to load SourceMap: Could not parse content for http://localhost:8080/17-es2015.84cb4530b2bf9abc0f0f.js.map: Unexpected token < in JSON at position 0_

>curl http://localhost:8081/projectname/taskname/metrics/xyz.jpeg -o file.jpeg

No such file, however this works:

`curl http://localhost:8081/project_name/task_name.48ae979b02414451b1e3fe9e54862f17/metrics/title/series/xyz.jpeg -o file.jpeg`

>curl http://localhost:8081/projectname/taskname/metrics/xyz.jpeg -o file.jpeg
 

The same as above if performed from the client side (after replacing localhost with the server ip).
I can obviously see the file within the **/title/series** subfolders.

Thanks!

**Comment by jkhenning** [comment]
Hi @majdzr ,

Sorry! This issue somehow got lost :disappointed: 

Apologies, `curl http://localhost:8081/projectname/taskname/metrics/xyz.jpeg -o file.jpeg` was obviously incorrect, however `http://localhost:8081/project_name/task_name.48ae979b02414451b1e3fe9e54862f17/metrics/title/series/xyz.jpeg` indeed looks like the right URL.

Can you try to browse to `http://localhost:8081/project_name/task_name.48ae979b02414451b1e3fe9e54862f17/metrics/title/series/xyz.jpeg` from the same browser instance on which the WebApp is running?

**Comment by mhashas** [comment]
@jkhenning Hi, I am facing the same issue. If I replace the server with localhost it does work

![Screenshot 2020-08-19 at 12 57 30](https://user-images.githubusercontent.com/13119609/90626889-be203e80-e21b-11ea-8be6-aa278c4f82ae.png)

**Comment by jkhenning** [comment]
Hi @mhashas,

If you get connection time out, this is usually due to some network configuration issue or firewall blocking your call.
Are you trying to access these images from the same machine running the server?

Also, did the experiment that generated these images run from the same machine or some other machine?
Assuming you're running your browser from the server machine, it seems the images were uploaded from some other machine using the server's external IP address, but that this address for some reason is not reachable from the server machine (but as expected, `localhost` works) - is that the case?

**Comment by mhashas** [comment]
@jkhenning 

> Are you trying to access these images from the same machine running the server?
No

> Also, did the experiment that generated these images run from the same machine or some other machine?
Some other machine 

I run the experiments on AWS and tunnel it to localhost

**Comment by jkhenning** [comment]
> I run the experiments on AWS and tunnel it to localhost

I assume the tunneling makes it possible to access via `localhost`, but your AWS network configuration either blocks port `8081`, or the server isn't reachable using the same IP.

Is it possible you ran the experiment on another AWS machine and used the server's private IP to access the server instead of the public AWS IP of the server machine?

When reporting images, the link is created using the file server's IP as configured in the local `trains.conf` file. So, if you configured the file server address using an IP address that was reachable from the training machine, this IP was embedded in the link. If the same IP is not reachable from the machine on which you're using to access the Trains Web UI, you won't be able to access the image...

**Comment by allegroai-git** [comment]
@mhashas please reopen if this is still an issue
