### ISSUE TITLE
Server Crashes -> Experiments Crash

### ISSUE THREAD

**Issue by rvardimon** [allegroai/clearml#187]
Hello,
Our Trains AWS server crashed (we don't know the reason).
The more problematic issue is that **this led to all of our training servers to crash**, at the same time.

We are using trains Version: 0.16.0, and not using the Trains agent, only occasional explicit reporting.
The explicit reporting functions (e.g. `report_scalar`) are all covered with try/except, and some of the experiments crash during training (not reporting at all, except probably for the auto uploading of stdout/stderr).

This is an urgent bug, since it makes our long/expensive experiments vulnerable to the Trains server.
Thanks

**Comment by jkhenning** [comment]
Hi @rvardimon,

In general, Trains should never crash, even if the server is not responding (it basically retries for a very long time).

Some information would help, such as:

- What Trains client version are you using?
- How did the training code crash? Can you send the console/log output?
- Did you install Trains Server 0.16 from scratch or did you upgrade from a previous version?
- Can you explain what does "Our Trains AWS server crashed" means?
  - Did the AWS instance fail?
  - Did the Trains Server stop responding to requests?
  - What did/do you see in the UI?

**Comment by rvardimon** [comment]
We are using `trains 0.16.0` client and server version is 0.15.1
We are still trying to understand what happened in the server, but it seems like it ran out of disk memory (had 8G to start with)

Log of machine 1:
```
2020-08-14 16:00:59,934 - Epoch[16] Batch [8140-8160]   Speed: 321.91 samples/sec       acc=0.794500    CE_loss=1.712807
2020-08-14 16:01:06,120 - Epoch[16] Batch [8160-8180]   Speed: 323.34 samples/sec       acc=0.780000    CE_loss=1.764167
2020-08-14 16:01:12,222 - Epoch[16] Batch [8180-8200]   Speed: 327.76 samples/sec       acc=0.795000    CE_loss=1.811525
```
and similar in other machines (the log crashed during training at the same time)
we didn't see any errors in the logs

Trains server is a prebuilt AWS server:
`allegroai-trains-server-0.15.1-366-248-c5c210e4-5094-4eb9-a613-a32c0378de31-ami-0bc20623da659a8cd.4 (ami-07b267ee71e8d2bad)`

* Did the AWS instance fail? no. seems like the server itself continued to run.

* Did the Trains Server stop responding to requests? it became impossible to log into the web interface. didn't check directly if it stopped responding to requests
* What did/do you see in the UI? we didn't get the normal login screen anymore, instead there was a screen asking for the user only (no longer asked for the password). but writing down the user and hitting ok didn't result in any response.

**Comment by bmartinn** [comment]
@rvardimon 

>We are still trying to understand what happened in the server, but it seems like it ran out of disk memory (had 8G to start with)

Yes, 8GB is the minimum for RAM not Disk ;)

Basically *Trains* will try to send the logs forever (well maybe not forever but for at least 24h).
The exception is getting 500 error reply (or other actual error reply codes) from the server.
I assume what happened is that you run out of disk space, and the server started reply 500 (error) because it could not ingest any more data (out of disk space). The thing is, you should have seen the errors on the local machines stderr ...

When you say, these are the logs... Where did you see them the console  on the machine running the experiment ?
(In any case, even if the server drops, regular console print should continue as usual, the log itself is sent in the background and is fully async. There is one exception, which is uploading artifacts/models , the upload itself is async in the background, but the registration (i.e. pointing to where the file is) is synchronous.

**Comment by rvardimon** [comment]
Hi
Good point about the logs. We were looking at the logs generated by the python logger, however it doesn't record all stderr automatically, so we could have missed the error msg. We also don't have access to the logs stored on the server, because since the incident, the trains server stopped working and we reinstalled it. So I'm afraid I cannot be more helpful.
However, if I may suggest a way to recreate the issue:
- start an experiment with trains (using `Task.init(...)`)
- shut down the server
I assume the client should crash.
and I think this is not the desired behavior, because for example we suffered from 8 p3 instances stopping in the middle of training. How about changing the behavior that instead of raising an exception, trains will print an error msg to stderr, sleep, and try contacting the server again after a while?

**Comment by bmartinn** [comment]
>    start an experiment with trains (using Task.init(...))
    shut down the server

This will cause Trains to continue and try to send logs (timeout fail, not returned error code from server).
In order to simulate the situation we need need to somehow make the server return 500 errors.
I'm also not sure what can be done if that is the case, other than report to stderr (where one would expect to get their errors).

As for crashing, I'm pretty sure most users would disagree. I would prefer to have the trained model, after 2 days of training, and not have the training process crash alongside the server :)

> trains will print an error msg to stderr, sleep, and try contacting the server again after a while?

We could add a configuration parameter, basically saying retry on all server errors

**Comment by rvardimon** [comment]
> As for crashing, I'm pretty sure most users would disagree. I would prefer to have the trained model, after 2 days of training, and not have the training process crash alongside the server :)

I think you got me wrong here, I am strongly opposed to the client crashing. The whole point of this issue is that server crashes ---> client crashes is very very bad. Right now, if the server returns 500 errors from whatever reason, all our experiments crash. As a user of trains I have no way to protect this (try/except etc) because everything happens behind the scenes. So what is the exact reason for which the server returned errors is the side point here, the main point that the training experiments should continue to run irrespective of the state of the server. At least that's my point of view.

We currently suspended all use of Trains until this gets resolved because the risk of getting experiments to crash because of server issues is unacceptable, and I very much hope it gets resolved soon, because Trains is highly useful for us.

**Comment by bmartinn** [comment]
@rvardimon the `trains` package will never crash a process (unless you aborted the task, in that case, obviously it will kill it :) )
Specifically to this issue, server returning a 500 error **will not** cause the `trains` package to crash the process.

You initially stated:

>The more problematic issue is that this led to all of our training servers to crash, at the same time.

What do you mean by crashed?! The fact the logs stopped coming in, is a by product of the `trains-server` being out of disk space, not because the `trains` client stopped trying to send logs. Do you have an exception log? Did the process hang? Did the process quit with a specific exit code?

What am I missing here?

> ... because Trains is highly useful for us.

Great to hear that! We need our users to help us make Trains better, that said this is a two way effort :)

**Comment by jkhenning** [comment]
Hi @rvardimon,

Any update on this issue?

**Comment by qwaxys** [comment]
Closing this issue and marking it as inactive for now, if you have any more questions feel free to open a new issue and link to this one.
