### ISSUE TITLE
pipeline example not working.

### ISSUE THREAD

**Issue by AndroZa0812** [allegroai/clearml#218]
I have cloned the pipeline example and I have got the following exception:
```
raise ValueError('Could not find base_task_project={} base_task_name={}'.format(
ValueError: Could not find base_task_project=examples base_task_name=pipeline step 1 dataset artifact
```
The error is strait forward, maybe the execution of the pipeline on my end is incorrect ? 
For context I am using python 3.8.5, and the execution line is: `python3 pipeline_controller.py`

**Comment by bmartinn** [comment]
Hi @AndroZa0812 

I'm assuming you are referring to this [example](https://github.com/allegroai/trains/blob/master/examples/pipeline/pipeline_controller.py).

In order to launch the pipeline, we have to make sure all the pipeline steps are in the system.
In order to do that, someone, somewhere sometime executed a code once and that created the initial experiment (Task).

Specifically in this example, you have to first run steps [1](https://github.com/allegroai/trains/blob/master/examples/pipeline/step1_dataset_artifact.py),[2](https://github.com/allegroai/trains/blob/master/examples/pipeline/step2_data_processing.py),[3](https://github.com/allegroai/trains/blob/master/examples/pipeline/step3_train_model.py) , they will each create its own task in the system.
Then you can run the pipeline, that clones those experiments and launches them (enqueues them into an execution queue).
Make sense ?

**Comment by AndroZa0812** [comment]
Oh thanks , it worked !
I have executed all the stages and then executed the pipeline and it worked. Very cool concept I must say .

**Comment by bmartinn** [comment]
> Very cool concept I must say .

Thank you @AndroZa0812 !
Feel free to tell your friend ;)
