### ISSUE TITLE
Additional keras model is uploaded but not referenced

### ISSUE THREAD

**Issue by n-Guard** [allegroai/clearml#252]
I'm using the `ModelCheckpoint()` callback with tensorflow.keras==2.3.1 and trains==0.16.2.
Now, with automatic logging enabled two models are being uploaded: one "regular" model (saved after training) and a "best model" from the `ModelCheckpoint(save_best_only=True)` callback.
So far, this is expected behavior but afterwards when I query the task with the two models, I cannot retrieve "best model" although both models are stored in the `<TASK-ID>/models` folder.
What is the correct way to get a local copy of this model?

**Comment by bmartinn** [comment]
Hi @n-Guard 
Querying all the models produced by a task:
``` python
executed_task = Task.get_task(task_id='aabbcc')
executed_task.models['output']  # type: List[trains.Model]
```
Notice, the returned value is a list of [Model](https://github.com/allegroai/trains/blob/91cbc161f4192f2146e7345a06c4fe1e9da21970/trains/model.py#L387) objects

For example, if you want to get the last model weights file (the "best model" in your case, since we have `save_best_only=True`) you can do:
``` python
print(executed_task.models['output'][-1].get_local_copy())
```

**Comment by n-Guard** [comment]
Hi @bmartinn,

thanks for your explanation!
The problem is that the list from `executed_task.models['output']` only contains one model instead of two.

**Comment by bmartinn** [comment]
I wonder if more than one model checkpoint was logged in the first place...
@n-Guard can you see any other models in the UI (belonging to the specific experiment)? 
(On the experiment table page, at the top there is a tab names "Models", all the models in the project should be listed there)

**Comment by n-Guard** [comment]
When I look at the "Models" tab, there is only one model present per experiment but when I look into the actual folder inside the `trains/data/PROJECT/fileserver/TASK-ID/models` directory both models are there.

I've created a short script to reproduce this behavior:
https://gist.github.com/n-Guard/a413a8b39c8f5087154b7a19add38959

**Comment by bmartinn** [comment]
Thank you @n-Guard , the code is a great help!
The bug is  verified 
Trains reuses the same model object even though the file name is different, the idea is to match the local storage , i.e. if you are overwriting the local file, the same will happen in the system, but here we see it reuses the model object, even though you saved the file under a different name.

**Comment by jkhenning** [comment]
Closing this as it was fixed long ago 🙂
