### ISSUE TITLE
Task recreating project stuck

### ISSUE THREAD

**Issue by valeriano-manassero** [allegroai/clearml#274]
Following sequence may drive to an unusable project state:

* run a task that creates a project
* archive the task
* delete the project
* run again the first task that should recreate the project

Result:
```
trains.backend_interface.session.SendError: Action failed <400/401: projects.get_by_id/v1.0 (Invalid project id: id=b8b44e6b070341f28312292dec50dfb2)> (project=b8b44e6b070341f28312292dec50dfb2)
```

**Comment by bmartinn** [comment]
Thanks @valeriano-manassero , I was able to reproduce the issue.
This is actually a bug in the reusing mechanism (i.e. not an actually bug in the backend system)
If you add `reuse_last_task_id=False` to your `Task.init(...)` call, it will not try to reuse the previous experiment, and will not fail due to an invalid reference project ID.
Regardless, I'll make sure it is fixed :)

**Comment by valeriano-manassero** [comment]
I tested this scenario again with latest ClearML version and it looks good.
