### ISSUE TITLE
Multi-Step Training and Custom Docker Image building

### ISSUE THREAD

**Issue by ErenBalatkan** [allegroai/clearml#276]
When working with base libraries, and no external custom dependencies, this is a great tool, but i feel like several things break when customization is needed.

I am not sure whether these are supported by ClearML or not, but i couldn't find information about these topics. So if they are supported, please let me know.

Problem 1 - Custom docker images. Right now it is designed to pull a base docker image from a given link. How about support for Dockerfiles and custom image building? That would really benefit us greatly.

Problem 2 - Startup scrips are designed to execute python files only. I suggest changing this to executing bash commands instead. Not only this would make this system compatible with even non-python projects to some degree, it would make it so that system is automatically compatible with already existing projects that rely on shell scripts for managing training without any needed code change.

**Comment by bmartinn** [comment]
Hi @ErenBalatkan

I'll start with the second issue, as I think it might solve the first as well

Regrading (2): I guess this is another flavor of #236 , am I missing something?
If it is, then you wil be happy to know that in the next version we will have docker bash init script, as part of the Task. This will in essence remove the need for a dockerfile support (see 1), as it will allow a user to add any `apt-get` alike install process before the code actually executes, and expand the capabilities of off-the-shelf dockers.

Regrading (1): Using docker files is limiting when combining the ClearML-Agent with Kubernetes (or any other container orchestration solution) as they all require a pre-built container image. The reasoning is that usually per project you have a container image already containing all the non-python software required for the setup, then what is changing is mostly python packages and code. Obviously if the underlying requirements changes you can always build another docker image. Since docker hub are kind enough to provide free docker image hosting this is really quite easy to do. That said, I can totally see your point where if we can alleviate the complexity and have the dockerfile automatically built and cached on the machine, it should be considered. See (2) as alternative solution 😄 

WDYT?

**Comment by ErenBalatkan** [comment]
That would be awesome and fix most of the issues i am facing.

In the project I am working on, it requires building a C++ module and connecting it to python. This is a very simple process that can be done with single command, having to pre-build image and host it on dockerhub would make process unnecessarily complicated. But update in next version will fix this issue so this can be considered solved.

One part still stands though, some of the code we deal with require multi-step initialization processes for experiment start-ups. For example, glow-tts
https://github.com/jaywalnut310/glow-tts/blob/master/train_ddi.sh

In this case, we arent running a single python file but actually running 2 python files in order to start our experiment. This isnt exactly part of the install process but it is part of the experimentation process. 

Is there any way to handle multi-step training code like this? 

BTW, Thanks for building such an awesome and useful project. I believe you guys are only few steps away from being extremely flexible and useful to many researchers and companies.

**Comment by bmartinn** [comment]
> In the project I am working on, it requires building a C++ module and connecting it to python. This is a very simple process that can be done with single command, having to pre-build image and host it on dockerhub would make process unnecessarily complicated, especially on research projects where the module that needs to be connected is frequently changing. But update in next version will fix this issue so this can be considered solved.

I can totally relate :)
BTW: I might have a temporary solution, if you have agents running Tasks for this project, you can configure a docker init script on all the workers. Set the `extra_docker_shell_script` in your [~/clearml.conf](https://github.com/allegroai/clearml-agent/blob/8fdb87f1f52bc29f5244d691979ebd162655a0b5/docs/clearml.conf#L124)

> Is there any way to handle multi-step training code like this? This isnt very common and can usually be handled by creating a new python file that does both operations. But out of box support for this would further increase flexibility and compatibility with already existing code.

I'm assuming this has to be executed on the same machine/docker one after the other.
And I guess you do not need to run it when your are developing the code (otherwise this would have been a simple function call).
Maybe in the main training script you could have:
``` python
import sys
from clearml import Tasl

if not Task.running_locally():
    # this code will only be executed when the agent is executing the Task
    os.system('{} init.py'.format(sys.executable))

# real training here
```

> BTW, Thanks for building such an awesome and useful project. I believe you guys are only few steps away from being extremely flexible and useful to many researchers and companies.

Your kind words warm our  ❤️  (they really do!). Feel free to spread the word :)

**Comment by ErenBalatkan** [comment]
Thanks,

Changed the name to a more descriptive one and closing the issue
