### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by vinh-cao** [allegroai/clearml#293]
Hi guys,

i am building a local clearml server behind a corporate proxy.
Since I have multiple computers, I can use one of them as ClearML server with adress like : **server.local:8008**
On an other computer, I have a running docker Agent agent.local. But the agent need internet to install packages, therefore I set `http_proxy` and `https_proxy` environment variables. But after the packages installation, the agent failes to Token, because I set the proxy:

> clearml_agent: ERROR: Failed getting token (error 404 from http://server.local:8008): Not Found

Is there any best practice to solve the problem or is there any workaround?

Thanks in advance.

**Comment by bmartinn** [comment]
Hi @vinh-cao 
I might be missing a few details on the setup.
1. Is the address 'server.local' resolved properly inside the docker agent ?
2. Do you need a proxy to get to the 'server.local'?
3. From what I understand you have to have a proxy to get to the public internet, is that configured inside the Agent docker? if it is, how is it configured?
4. From Inside the Agent docker, can you run `curl http://server.local:8008` and `curl http://server.local:8080` ?

**Comment by vinh-cao** [comment]
Hi Martin,

thanks for your response. In the draft below, I have a server and an agent within a local network. The agent1 can successfully call `clearml-agent init` because they both are in the local network.

When I start the agent service like `clearml-agent daemon --queue default --docker base_image -e http_proxy=$http_proxy` and invoke a task, a new container get spawned and packages need to be installed. To install the packages, the task/experiment container need internet access. Therefore I set environment parameter http_proxy and https_proxy. After successfully installing the packages, the experiment container want to do `init` again with the API server. But the init fails because the DNS cannot resolve the name `server.local`.

Do you know how I can solve it?

![image](https://user-images.githubusercontent.com/58787002/105718225-4a4c3580-5f21-11eb-8c8a-8c5c6930b6d4.png)

**Comment by bmartinn** [comment]
Hi @vinh-cao 

> When I start the agent service like clearml-agent daemon --queue default --docker base_image -e http_proxy=$http_proxy ...

Since in your setup you always need to add the http_proxy settings, I suggest you add it to the [extra_docker_arguments](https://github.com/allegroai/clearml-agent/blob/822984301889327ae1a703ffdc56470ad006a951/docs/clearml.conf#L121)
This will make sure that regardless of the docker image you select the agent will always add this flag to the execution (when you just add the flag in the arguments, they become the default docker image parameters, but if you change the docker image from the UI you basically override them)
```
extra_docker_arguments = ["-e", "http_proxy=PROXY_IP_ADDRESS_HERE"]
```

Based on your description it seems like the pip is working correctly and is using the correct https_proxy.
I'm assuming the issue is that when clearml is trying to authenticate with `server.local` the connection is passed to the proxy server, and then we get the error. Basically adding the following will make sure all connections to the `server.local` will not go through the proxy:

```
extra_docker_arguments = ["-e", "http_proxy=PROXY_IP_ADDRESS_HERE", "-e", "NO_PROXY=server.local"]
```

**Comment by vinh-cao** [comment]
Thank you, Martin. Adding the extra docker arguments solved my problem :)
