### ISSUE TITLE
agent doesn't override default_output_uri from original task

### ISSUE THREAD

**Issue by glemarivero** [allegroai/clearml#298]
clearml version: 0.17.4
clearml-agent version: 0.17.1

Except for the explicit changes described here, I'm using the default config file in both servers

I create a task in server 1, `output_uri` is not set in the initialization of the task.
server 1 has in the config file:
`default_output_uri: "/home/glema/clearml"`
run the task
Model is saved in the "/home/glema/clearml" directory

clone the task
enqueue it

Agent that runs in GCP has in the config file:
`default_output_uri: "gs://glema_sandbox"`
Agent pulls task from queue, runs it, and saves the model in "/home/glema/clearml" directory (this is actually possible, because agent is being run as root)

Repeat the procedure, this time clearing the `default_output_uri` in server 1 config's file before running the task
GCP agent pulls task from queue, runs it, and saves the model in "gs://glema_sandbox" directory

**Comment by bmartinn** [comment]
Hi @glemarivero 
Yes, this behavior is "by design", basically `default_output_uri` is the default value, if `output_uri` is not defined on the Task.
Once `output_uri` is used (whether by using the default value or if set manually), it is stored on the Task itself, hence when cloning the Task we also clone the `output_uri` field.

A couple of solutions:
1. You can edit the `output_uri` in the UI, under the "Execution" tab, "Details" section, "Output destination" section
2. Maybe we can introduce `force_output_uri` into the `~/clearml.conf`, making sure we can always override this field in the agent itself.

WDYT?

**Comment by glemarivero** [comment]
Ah, good to know. I just have to create a new queue for my local server then.

Thanks!
