### ISSUE TITLE
ClearML is not saving scalars/images when using Tensorflow Object detection API - TF2.2

### ISSUE THREAD

**Issue by glemarivero** [allegroai/clearml#321]
This issue is related to this thread: https://clearml.slack.com/archives/CTK20V944/p1610457717141400

To reproduce:
git clone https://github.com/glemarivero/raccoon_dataset.git
setup a virtualenv
run `sh autoinstall.sh`
Generate tfrecords:
```
python generate_tfrecord.py --output_path images.tfrecord --csv_input raccoon_labels.csv --image_dir images
```
Run training:
```
python model_main_tf2.py --model_dir=models/ --pipeline_config_path=pipeline.config
```

**Comment by bmartinn** [comment]
Thanks @glemarivero , I will try to reproduce it and will update back here.

**Comment by bmartinn** [comment]
Hi @glemarivero Thank you again for the code! I am able to run the training session.
I think it reproduces the issue, as I'm only getting the "steps_per_sec" scalar graph, and I'm missing the "Loss/BoxClassifierLoss/localization_loss" etc.
Let me dig deeper and see what's going on.

**Comment by asmithaxe** [comment]
Just to add my +1, the scenario just described by @bmartinn is the same that I experience.

**Comment by bmartinn** [comment]
Okay guys I now understand what's going on.

`object_detection` was originally built on TF 1.x, when they added TF2 support, they used the compatibility layer `tensorflow.compat.v1` . Usually this works well as it also uses the TB 1.x  summary writer and thus `clearml` is able to detect and log all scalars/tensors etc. Unfortunately what happened with `object_detection`  is they are using a mixture of TF 1.x (non eager mode) code, with some eager mode reporting using the TF2 (eager mode oriented) Summary Writer.

The outcome of that is that all the new "eager-mode" reports are logged correctly by `clearml,`, for example the "steps_per_sec", but all original scalars like "Loss/..." are non eager-mode reports that we cannot be parse with the eager mode summary writer.

Supporting this mixture of non eager-mode and eager-mode reporting on the same eager-mode summary writer might be challenging (although hopefully doable). The question is do we want to go down this rabbit hole. Basically what I'm trying to figure out is whether `object_detection` is going to be adapted to TF2, or is it a static repository that will stay with this TF1/TF2 mix.

WDYT?

**Comment by asmithaxe** [comment]
Great job debugging!

I've taken a quick look through the TF code, and my guess is that they intend moving in that direction (full TF2), but it would be impossible to guess how long that will take them. So maybe the question then becomes what is the impact on Allegro and the need/desire for a temporary fix for this broken feature.

I don't represent a big opportunity for you guys, so I wouldn't blame you guys for giving this a low priority. I'm the only one in my organisation using TFOD at the moment. I had hoped to use my TFOD work as the foundation of a presentation to the rest of the data science team on the use of ClearML, however I can always go with random point classification instead of object detection for the purposes of that demonstration. But I would REALLY love to see ClearML and TFOD work. You guys have a great product.

**Comment by glemarivero** [comment]
Oh that's too bad! I see, so since you have already debugged it, do you know exactly where does the eager-mode start and non eager mode ends?
Just want to know if I can modify the library so that it works with ClearML. I'm too using this project to show ClearML capabilities in my company..

**Comment by bmartinn** [comment]
@asmithaxe your kind words are much appreciated, thank you !

> Just want to know if I can modify the library so that it works with ClearML. I'm too using TFOD library to show ClearML capabilities in my company..

@glemarivero I think this is doable, if you take a look at `object_lib_v2.py` [eager_train_step(...)](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L186)
It says right in the function name, it supports eager-mode, but when it is used in [train_loop(...)](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L616) it is called as TF1 graph-mode function. I think the root cause is this [@tf.function  _dist_train_step(...)](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L644). Basically if instead of decorating with `@tf.function` , it will be part of an eager mode execution loop, everything should work.


Now for the good news 🎉 🎊 
Just add the following line at the top of your code (before any TF graph initialization), and TF2 will magically move all graph-mode functions into eager-mode functions. With everything in eager-mode `clearml` is catching all TB reports as usual :)
```python
import tensorflow
# this line will make it run in eager-mode, which will make clearml catch all TB logs :)
tensorflow.config.experimental_run_functions_eagerly(True)
```


BTW: for future reference, I was able to reproduce the behavior with the code snippet below (it is awful TF code, but it does prepuce the issue and the fix ;) 

```python
import tensorflow

from clearml import Task
task = Task.init('examples', 'TB 1 & 2 mix')

# this line will make it run in eager-mode, which will make clearml catch all TB logs :)
tensorflow.config.experimental_run_functions_eagerly(True)

writer = tensorflow.summary.create_file_writer("models/test/")

@tensorflow.function
def my_func(step):
    # other model code would go here
    tensorflow.summary.scalar("my_metric", 0.5, step=step)

with writer.as_default():
    for step in range(100):
        my_func(step)
        writer.flush()
```

**Comment by asmithaxe** [comment]
First the good news: I confirm the `tensorflow.config.experimental_run_functions_eagerly(True)` call allows ClearML to catch the TensorBoard logs. 

Now the bad news, the `steps_per_sec` drops from 3 - 4 per second (non-eager mode on old 1060 GPU) to around 0.6 per second (eager mode, same GPU). I am fine tuning a `ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8` from the TF Zoo.

Any thoughts if the problem is (a) extra processing added by ClearML; or (b) inefficiencies in TensorFlow for running the entire training in eager mode? Hopefully (b), as that probably gives more scope for solving the problem, perhaps by removing the decorating `@tf.function`.

**Comment by glemarivero** [comment]
Hi! Thanks! I can also confirm that it works, but I didn't realize the steps per second issue (I ran it in my personal laptop with no GPU)..So we can't use it in training mode, but at least we will be able to use it in eval mode.. pretty cool!

**Comment by bmartinn** [comment]
I can verify that:
1. Switching to eager mode slows down the training process (x2 on my machine)
2. This is an eager-mode issue, even without `clearml` we get the same slowdown

Good news, if you are willing to change the `object_lib_v2.py` code, you can just move the scalar/image reporting outside of the `@tf.function`  (no need to add the magic `tf.config.experimental_run_functions_eagerly(True)` call). 

I can verify that not only it has no effect on training speed, it also solves the cleamrl autologging.

Basically mark-out these sections [losses_dict](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L299) ,  [learning_rate](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L310) & [train_input_images](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L311) in `eager_train_step()`, 
then instead of [return total_loss](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L316), `return total_loss, losses_dict, learning_rate, features[fields.InputDataFields.image]` and propagate all variables to the main [training loop](https://github.com/tensorflow/models/blob/f7260d3eaa0698ec65af061732f2b4850bfb27a6/research/object_detection/model_lib_v2.py#L667)
```python
loss, losses_dict, learning_rate, debug_images = _dist_train_step(train_input_iter)
tf.compat.v2.summary.scalar('learning_rate', learning_rate, step=global_step)
for loss_type in losses_dict:
  tf.compat.v2.summary.scalar(
      loss_type, losses_dict[loss_type], step=global_step)
tf.compat.v2.summary.image(
    name='train_input_images',
    step=global_step,
    data=debug_images,
    max_outputs=3)

```

**Comment by glemarivero** [comment]
oh, that's awesome! do you have the complete file? I tried to make those changes but I'm getting this error:
```    TypeError: Expected float32, got <tf.Tensor 'Loss/BoxClassifierLoss/classification_loss:0' shape=() dtype=float32> of type 'Tensor' instead.
```
Thanks!

**Comment by bmartinn** [comment]
Might be a bit messy, but should work :)

[model_lib_v2.py.zip](https://github.com/allegroai/clearml/files/6225249/model_lib_v2.py.zip)

**Comment by asmithaxe** [comment]
Thanks @bmartinn . The file you posted is a slightly older version, but it was great for following your instructions above and applying to the latest version of the file.

I confirm that the autologging problem is resolved with these changes.

The training speed is slightly slower (2.5 - 3 steps per second) than standard (3.5 - 4 steps per second), but a HUGE improvement over running completely in eager mode (~0.6 steps per second), and not related to ClearML so not at issue anyway.

Thank you.

**Comment by glemarivero** [comment]
Thanks @bmartinn ! 
@asmithaxe  it is an older version probably because he followed my installation instructions, and there is a git checkout to an older commit in that repo.
I also tried it and it works great 🙂

**Comment by bmartinn** [comment]
Guys do you see any reason why we should not PR this fix to the TF models  repository ?
It sounds like moving the reporting to a single location in the main loop is actually the right thing to do, regardless of the upside of `clearml` detecting all the reports.
wdyt?

**Comment by asmithaxe** [comment]
I think that's a good idea. Worst case is that they reject it. Biggest challenge, I think, would be wording a suitable Issue report describing why it's a problem for them. Or do you think the idea of "moving the reporting to a single location in the main loop" should be sufficient?

**Comment by glemarivero** [comment]
That would be nice to have indeed! Have you also changed the eval mode @asmithaxe ?
Thanks!

**Comment by asmithaxe** [comment]
I'll post my code later today for review. I can't access it right now (dual boot).

**Comment by asmithaxe** [comment]
Sorry to take so long. See change here: https://github.com/asmithaxe/models/commit/f8814b3ebd96934733acd436a523df220b2fc70a#diff-d6241ffb0103c18b5bea432efe07a10a271943fbf526fd87b50922a28de1cac5

**Comment by bmartinn** [comment]
Thanks @asmithaxe, looking good.
I would add an argument to control the reporting frequency of debug images, to save on TB entries (e.g `image_report_freq` report debug image samples  every X training steps).
wdyt?
