### ISSUE TITLE
Can't register via GitHub: Value Combination already exists

### ISSUE THREAD

**Issue by RobinBaumann** [allegroai/clearml#344]
Hi folks!

I am trying to sign up for CleaML via GitHub, but the form keeps showing: Value combination already exists

However, I am pretty sure that I have not signed up yet. When I try to log in via E-Mail and request a password, I don't get an E-Mail.

Also, when I try to log in via GitHub, I get: No account exists. Use the provider you signed up with or sign up to create a new account

**Comment by jkhenning** [comment]
Hi @RobinBaumann,

When exactly did you try? I've tried searching the logs but I can't find any error reported.

Since this relates to the ClearML Service (and not to the open-source ClearML package or server), and since an interactive discussion will probably be more effective, I suggest we continue the discussion in the ClearML [Slack Channel](https://join.slack.com/t/clearml/shared_invite/zt-c0t13pty-aVUZZW1TSSSg2vyIGVPBhg) - either start a discussion thread in the `#clearml-community` channel and I'll pick it up, or just DM me there 🙂

**Comment by jkhenning** [comment]
@RobinBaumann  good news 🙂 

I've just found the error, investigating now, will update soon...

**Comment by RobinBaumann** [comment]
> Hi @RobinBaumann,
> 
> When exactly did you try? I've tried searching the logs but I can't find any error reported.
> 
> Since this relates to the ClearML Service (and not to the open-source ClearML package or server), and since an interactive discussion will probably be more effective, I suggest we continue the discussion in the ClearML [Slack Channel](https://join.slack.com/t/clearml/shared_invite/zt-c0t13pty-aVUZZW1TSSSg2vyIGVPBhg) - either start a discussion thread in the `#clearml-community` channel and I'll pick it up, or just DM me there 🙂

Thanks for the fast reply! I am very busy today. Just let me know in this thread whenever you found something and if we need to discuss this in slack. I will contact you then.

**Comment by jkhenning** [comment]
Hi @RobinBaumann,

Good news - server was updated with a fix. Please try again and let me know if it works 🙂

**Comment by RobinBaumann** [comment]
> Hi @RobinBaumann,
> 
> Good news - server was updated with a fix. Please try again and let me know if it works 🙂

@jkhenning  Wow, that was fast! 

Thank you! it works now like a charm.
