### ISSUE TITLE
End script without ending task

### ISSUE THREAD

**Issue by aschmiri** [allegroai/clearml#406]
I initialize a task locally via `Task.init()` and then submit training jobs from the python script to the SLURM cluster. Each SLURM job knows the task ID and obtains the task via `Task.get_task()`. However, as soon as the main script finishes, the slurm scripts fail stating:

```
- clearml.Task - WARNING - ### TASK STOPPED - USER ABORTED - STATUS CHANGED ###
```

Is there a way to end the main script without changing the task status?

**Comment by bmartinn** [comment]
Hi @aschmiri 
Hmm lots to unpack here :)
Side note: If you only need to create a Job (as opposed to auto logging with Task.init), use [Task.create](https://clear.ml/docs/latest/docs/references/sdk/task#taskcreate), then `task.mark_started()`,  to change it to "running".

Are the multiple SLURM jobs using the main Task only for reporting ? or would you want some automagic ?

1. Task reporting only:
In the main Task you can do:
```python
from clearml import Task
task = Task.init('project', 'main task')
# do some stuff
task_id = task.id
# flush and close the main Task
task.close()

# mark the closed Task as running, so that the SLURM jobs could report to it.
Task.get_task(task_id=task_id).mark_started(force=True)
# pass task_id to SLURM job and leave process
```

Then in the SLURM Jobs you can:

```python
from clearml import Task

task = Task.get_task(task_id='THE TASK_ID WE PASSED')
task.get_logger().report_scalars(...)
"


2. Automagic in remote SLURM jobs (allowing us to control parameters from the UI)
```python
from clearml import Task
task = Task.init('project', 'main task')
params = {'stuff' : 'to do'}
task.connect(params)
task_id = task.id
# flush and close the main Task
task.close()

# mark the closed Task as running, so that the SLURM jobs could report to it.
Task.get_task(task_id=task_id).mark_started(force=True)
# pass task_id to SLURM job and leave process
```
In the remote SLURM Job:

```python
from clearml import Task

Task.debug_simulate_remote_task(task_id='THE TASK_ID WE PASSED')
# no need to worry about passing arguments to Task.init, it will ignore them becuase it will take the data from the existing Task_id
task.init()

params = {}
task.connect(params)
print(params)  # would show {'stuff' : 'to do'}

# full automagic in place, any tensorboard / matplotlib are reported, console output etc.
# of course you can also use task.get_logger()
```

**Comment by aschmiri** [comment]
Excellent, that works, thanks a lot! Only remaining issue is that I want to prevent the SLURM jobs from auto-uploading the model files (as this makes training much slower). I defined `auto_connect_frameworks=False` in `init()` but it doesn't seem to be passed on to the SLURM jobs. Or is this the wrong command altogether?

**Comment by aschmiri** [comment]
One other thing, the Task stays as "Running" after the last Job finished. How is this solved with multiple SLURM jobs (without knowing which one will finish last - is there some sort of instance counting?)

**Comment by bmartinn** [comment]
> I defined auto_connect_frameworks=False in init() but it doesn't ...

Make sure this is the way it is called inside the actual SLURM job (it has no effect when only called on the "master" job)
Also notice you have a finer granularity control basically `Task.init(..., 'auto_connect_frameworks={'pytorch': False})' will only skip auto uploading the models but will still log the tensorboard. See [docs](https://clear.ml/docs/latest/docs/references/sdk/task#taskinit)

> One other thing, the Task stays as "Running" after the last Job finished. How is this solved with multiple SLURM jobs 

This is a good question...
First notice, that the Task activity [watchdog](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_config#non-responsive-task-watchdog) will automatically set the Task to aborted, after two (default) hours of inactivity (no reports).
Is there a known number of instances ? What I'm thinking is maybe you could add some logic into your code to "stop" itself ? Then use ClearML to sync the reference counter in some atomic alike manner. The issue is ClearML is not actually aware of the number of multiple instances...
Another option is to leave the "master" process alive, and make sure it monitors the progress of all the SLURM jobs ?
wdyt?

**Comment by aschmiri** [comment]
Calling `init()` in the Slurm job solved the first issue (before I only called `get_task()`).

Regarding the stopping issue, I found a workaround. The master process will usually be stopped, but I always have a "merging" script called after the SLURM trainings, which now ends the task.

So all issues addressed, thanks a lot!

**Comment by bmartinn** [comment]
> The master process will usually be stopped, but I always have a "merging" script called after the SLURM trainings, which now ends the task.

Nice!!
