### ISSUE TITLE
How to execute pipelines partially?

### ISSUE THREAD

**Issue by kirillfish** [allegroai/clearml#415]
Suppose I connect several tasks into a pipeline using `PipelineController`. At some point, one of the tasks fails and the pipeline terminates. I see it on Execution Flow chart in web UI, but there seems to be no easy way to pick up where it left off.

The question is, how do I re-launch the failed parts of the pipeline from the web UI? 

If it is not possible, what is the most canonical way to do it from the pipeline initialization code? Using `pre_execute_callback`, running `get_processed_nodes()`  and fetching task ids which have failed?

**Comment by kirillfish** [comment]
I think this is a very important feature - be able to relaunch a pipeline from a new commit, skipping all passed steps

**Comment by kirillfish** [comment]
I see, `cache_executed_step=True` does exactly that.

**Comment by bmartinn** [comment]
Hi @kirillfish 
Nice catch, yes `cache_executed_step` allows you to reuse/cache previously executed steps of the pipeline. Notice that if the Task has git repo reference but no specific git commit ID (for example "latest from 'main' branch"), the Task will not be cached, because it has no way of knowing if the code base changed.

You can also clone the `PipelineController` Task in the web UI, under "Configuration" -> "Hyper Parameters" -> "Pipeline" , you will have `continue_pipeline=False`. If you change it to True it will continue from where it stopped. Also notice the state of the pipeline and it's configuration is stored under "Configuration Object"->"Pipeline". Per pipeline step you have an entry with the full configuration and execution step, for example:
```
stage_process {
  base_task_id = "4d5f7ddcc2ef43e0a9eba5bd3952a878"
  queue = null
  parents = ["stage_data"]
  timeout = null
  parameters {
    General/dataset_url = "${stage_data.artifacts.dataset.url}"
    General/test_size = 0.25
  }
  task_overrides = null
  executed = "00a1f44a34b24f49b88393f54baa579a"
  clone_task = true
  skip_job = false
  cache_executed_step = false
}
```
If you change the `executed = "00a1f44a34b24f49b88393f54baa579a"` to `executed = null` , this step will be reexecuted, otherwise it knows the execution of this step is in Task ID=00a1f44a34b24f49b88393f54baa579a.
Make sense ?

**Comment by kirillfish** [comment]
Thank you! makes perfect sense

Do `continue_pipeline = True` and `executed = null` work with "latest from branch" or they require a specific commit ID, like `cache_executed_step`?

**Comment by bmartinn** [comment]
> Do continue_pipeline = True and executed = null work with "latest from branch" or they require a specific commit ...

Already out including the `cache_executed_step` :) 
```
pip install clearml==1.0.5
```
