### ISSUE TITLE
logger.report_matrix extra_layout does not pass to plotly

### ISSUE THREAD

**Issue by navotoz** [allegroai/clearml#559]
Hello

I'm trying to constrain the color range (and thus the colorbar values).
When I try:
logger.report_matrix(..., extra_layout={'color_continuous_scale': 'Bluered', 'range_color': [0, 0.2]})
The matrices are reported, but the range of color remains the same - scaled [min,max] of the matrix.

Thanks for all your work! ClearML helps me a lot.

**Comment by bmartinn** [comment]
Thanks @navotoz 
Notice that `extra_layout` is the layout for the Javascript plotly objects interface (not the pythonic one)
This means that in order to configure the matrix plotly representation you need to pass these configuration values, see details [here](https://plotly.com/javascript/reference/heatmap/)
Specifically to your example, this would mean:
```
extra_layout={'colorscale': 'bluered', 'zmin': 0, 'zmax': 0.2}
```

Unfortunately all that said, you are still correct there is a bug and this extra layout is not passed into the correct attribute, fix will be applied shortly :) 

As a reference, this issue can be reproduced and tested with the following example code:
https://github.com/allegroai/clearml/blob/e182c188e0ceca939fa7ba8f5657228136f3ab1f/examples/reporting/scatter_hist_confusion_mat_reporting.py#L49
replacing with:
```python
    logger.report_matrix(
        "example_confusion",
        "ignored",
        iteration=iteration,
        matrix=confusion,
        xaxis="title X",
        yaxis="title Y",
        extra_layout={'colorscale': 'bluered', 'zmin': 0, 'zmax': 0.2}
    )
```

**Comment by navotoz** [comment]
I'll wait for the fix. Also, I suggest adding a note about extra_layout being JS in [report_matrix](https://clear.ml/docs/latest/docs/references/sdk/logger#report_matrix) docs.
Thanks for your answer!

**Comment by bmartinn** [comment]
Thanks @navotoz , we also added the correct references in the docstring.
Feel free to verify it works with your code
```
git install git+https://github.com/allegroai/clearml.git
```

**Comment by navotoz** [comment]
Hi

I reinstalled from source but it still doesn't work.
I tried:
`extra_layout={'colorscale': 'Bluered', 'zmin': 0, 'zmax': 0.2}`
`extra_layout={'colorscale': 'bluered', 'zmin': 0, 'zmax': 0.2}`
`extra_layout={'colorscale': 'bluered'}`
`extra_layout={'colorscale': 'Bluered'}`
`extra_layout={'cmin': 0, 'cmax': 0.2}`
`extra_layout={'marker':{'cmin': 0, 'cmax': 0.2}}`
without success.

**Comment by jkhenning** [comment]
Closing this as this was already released. Please reopen if required.
