### ISSUE TITLE
How to delete configuration object with hard code

### ISSUE THREAD

**Issue by RickyChenTaiwan** [allegroai/clearml#625]
Dear All,

I used connect_configuration method to create the dictionary in WebApp. ### **How to delete configuration object after creating "test dict"?**
Thanks.

Here is my code:
  `  
  t = Task.get_task(ID)
  t.started() 
  dict1_test = {} 
  dict_test = {"Rick": 123, "Megg": 456, "Snow": 789}
  dict1_test["Big Pin"] = dict_test

  ##put dict format into CONFIGURATION tab
  my_params = t.connect_configuration(dict1_test, name="test dict", description="configuration testing")
  print("print my_params: ", my_params)
  t.completed()
  `

  Best regards,

**Comment by jkhenning** [comment]
Hi @RickyChenTaiwan,

The whole purpose for `connect` is to sync your code with the server - why would you need to delete this section?

**Comment by RickyChenTaiwan** [comment]
Hi @jkhenning 

Because I treat CONFIGURATION tab as storage, it can add/delete items.

**Comment by jkhenning** [comment]
The configuration section was not designed a storage, so I would not advise using it for this purpose - perhaps you can use the artifacts support for that?

**Comment by RickyChenTaiwan** [comment]
Hi @jkhenning,

Thanks for your suggestion.
"perhaps you can use the artifacts support for that?" => you mean I can add/delete items in ARTIFACTS tab?

**Comment by jkhenning** [comment]
You can, but still, I'm not sure this will work over time - in ClearML, experiments (or tasks) are not meant to serve as storage space, and have different size limitations. Why not simply use a standard object storage for that?

**Comment by RickyChenTaiwan** [comment]
Hi @jkhenning,

Thanks for your advice.
Sorry, I am not familiar with ClearML actually.
Why not simply use a standard object storage for that? => what is the meaning of using a standard object storage?

**Comment by jkhenning** [comment]
> what is the meaning of using a standard object storage?
Uploading your files to an S3 bucket using the ClearML StorageManager, for example

**Comment by RickyChenTaiwan** [comment]
Hi @jkhenning ,

thanks for your detailed explanation, let me think about how to do it.

Best regards,

**Comment by Youyoun** [comment]
Hi @jkhenning , I currently have the same issue. I would like to delete a configuration object that was added through `connect_configuration`. I use hydra and clearml for my experiments, and I prefer logging the hydra file in clearml in order to have my metrics and my hydra config on the same interface. I have some tasks with a few duplicate configuration objects (due to a miscalculation on my part), and I would like to remove them from the tasks. Is there any way to do so using the provided API ? Thank you for you answer !

**Comment by ainoam** [comment]
@Youyoun There's no built-in configuration removal method since, as @jkhenning mentioned in previous comments, the task's configuration records the values used for execution and so should not be modified after the fact.

Having said that, and while definitely not recommended, you can always forcefully modify the stored object to reflect whichever content you need, similar as clearml [updates](https://github.com/allegroai/clearml/blob/972696450e21820a2e278d359dc9421ca18922d0/clearml/backend_interface/task/task.py#L2620) it's stored configuration.

**Comment by Youyoun** [comment]
Thanks for the answer ! I understand that this is a design choice. I already fixed my error and will keep it in mind for my next XPs
