### ISSUE TITLE
Adding support for DataFrame artifacts in a Parquet format

### ISSUE THREAD

**Issue by sephib** [allegroai/clearml#634]
Hi,
This issue is following the thread in [clearml slack](https://clearml.slack.com/archives/C01H5VAUZ8R/p1647887124482119)
The idea is for adding an option to save DataFrame artifacts as parquet file.
Currently, the Artifact class identifies if the artifact is an instance of `pd.DataFrame` and then saves it [to a csv](https://github.com/allegroai/clearml/blob/5f1345b148588d0a3d5f0c50c2c71737fa9af221/clearml/binding/artifacts.py#L375).

- What should be the strategy/architecture for adding such functionality assuming we use the [to_parquet](https://pandas.pydata.org/pandas-docs/version/1.1/reference/api/pandas.DataFrame.to_parquet.html)?
- An option is to add the user control for the `serialization_format` via some key in the [metadata](https://github.com/allegroai/clearml/blob/5f1345b148588d0a3d5f0c50c2c71737fa9af221/clearml/task.py#L1634) that is passed to the upload_artifact function.
- The   `serialization_format` could be added to the [upload_artifacts](https://github.com/allegroai/clearml/blob/5f1345b148588d0a3d5f0c50c2c71737fa9af221/clearml/binding/artifacts.py#L310)  function that will cover auto pickle usecase, as well as add the ability to control the specific internal serialization (like in the pandas case, but could be for images as well).
- The  `serialization_format` should be for several formats (not only DataFrames) (I guess numpy would also benefit, and PIL.Image etc.)

**Comment by erezalg** [comment]
Hi @sephib,

So what we're planning to do is, as you suggested, add a "format" parameter which will take the format you'll save your data object in clearml. We plan to broaden this more than just parquet (for for instance, a dataframe can be parquet or csv). 

We'll update here once a ClearML package with the fix is ready.

**Comment by erezalg** [comment]
Hi @sephib,

So what we're planning to do is, as you suggested, add a "format" parameter which will take the format you'll save your data object in clearml. We plan to broaden this more than just parquet (for for instance, a dataframe can be parquet or csv). 

We'll update here once a ClearML package with the fix is ready.

**Comment by erezalg** [comment]
Hi @sephib, we just release clearml 1.4.0 that adds the ability to chose the artifact saved foramt :) 
in upload_artifact() method you'll find the "format" parameter, it allows you to save to any (hopefully :smile: ) format supported by the data type.

Let me know if it works!

**Comment by jkhenning** [comment]
Hi @sephib, closing this. Please re-open if required.
