### ISSUE TITLE
bad project name prevents image logging 

### ISSUE THREAD

**Issue by elinep** [allegroai/clearml#70]
Hello trains team,

I noticed a minor issue with image logging when task's name contains special characters.

Here is an example with the **manual_reporting.py** example from trains package. I inserted a ":" in the project name, images are no longer available.

https://demoapp.trains.allegro.ai/projects/1ea2e0b01a7c478699c42977650fdce2/experiments/ef91e629e18d40c9b521c5f9656050e4/output/debugImages

**Comment by bmartinn** [comment]
Hi @elinep , 

You are correct and we were able reproduce the bug.

This issue actually relates to how the trains file server stores the debug images (or for that matter any 
other artifact). Since the project name is used as a folder on the trains-server back-end storage (for easy maintenance), any POSIX forbidden characters will cause the file server to fail storing the artifacts/images.

We will run some tests and update here on the design decision.

Notice that if you were to configure the debug images to be uploaded to an object store instead (like S3/GS etc.) the links would work.

**Comment by allegroai-git** [comment]
@elinep I believe this was solved way back in Trains v0.13.0 and should be working fine today. Please re-open if this is still an issue.
