### ISSUE TITLE
Set default output URI per project

### ISSUE THREAD

**Issue by schiegl** [allegroai/clearml#734]
Is there a way to set the default output URI on a per project basis on the ClearML server? The reason I find this interesting, is that people often forget to set the output URI when working with tasks/dataset and then artifacts get uploaded to disk instead of the output URI.

**Comment by erezalg** [comment]
Hi @schiegl,

Just making sure you're aware that you can set output_uri in the clearml.conf so that it will by default upload to wherever you point and not saved to disk.

If you need a per-project output_uri, we're working on adding an API call that will allow you to set the default upload destination per project.

**Comment by schiegl** [comment]
Yes, I'm aware of that. I guess a workaround for now would be to store new `clearml.conf` per project.

**Comment by erezalg** [comment]
@schiegl,

That might be a temporary workaround. We'll try to release a new version as soon as we can that will allow you to set the project's default upload destination with code.

**Comment by pollfly** [comment]
Hey @schiegl! Just letting you know that this issue has been resolved in the recently released [v1.7.0](https://github.com/allegroai/clearml/releases/tag/v1.7.0). Let us know if there are any issues :)

**Comment by schiegl** [comment]
Good news! I will let you know if anything comes up.

**Comment by jkhenning** [comment]
Closing this issue. Please reopen if it's still relevant.
