### ISSUE TITLE
Add more filters in the popup to choose compared experiments

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml#795]
## Proposal Summary

Hi, in the "Choose compared experiments" view of the WebUI, would it be possible to add a toggle to include archived experiments in the results of the search? Also add the task type field?

## Motivation
I would like to compare an experiment with archived experiments, and filter out some experiment types

## Related Discussion
[If this continues a slack thread, please provide a link to the original slack thread. ](https://clearml.slack.com/archives/CTK20V944/p1665144613020709)

**Comment by ainoam** [comment]
Thanks for the suggestion @H4dr1en. We'll try to add archive access it to one of the upcoming versions.

Re: Task types, this is already part of the existing UI (at least, since v1.2) - no?

![image](https://user-images.githubusercontent.com/51905810/194757491-b0047b4e-a289-4416-955e-2571004ba914.png)

**Comment by H4dr1en** [comment]
Hi @ainoam , yes indeed, sorry I missed that!

**Comment by pollfly** [comment]
Hey @H4dr1en! [clearml-server v1.10](https://github.com/allegroai/clearml-server/releases/tag/v1.10) is now supporting archived experiment inclusion in experiment comparison
