### ISSUE TITLE
Plots in overview

### ISSUE THREAD

**Issue by PierreSnell** [allegroai/clearml#839]
## Proposal Summary
Having a way to add plots in overview like we're able to have metrics. 

## Motivation
To have a quick glance on the project results. Metrics are perfects but sometimes a confusion matrix or a table helps more. 

Have a great day.

**Comment by ainoam** [comment]
Thanks for suggesting @PierreSnell.
It just so happens that the next version of ClearML scheduled for EOY would introduce the ability create individual markdown reports, including support to embed any of your experiments outputs: plots, debug samples and even comparison graphs!!

We'll let you know when it's out :)

**Comment by pollfly** [comment]
Hey @PierreSnell! clearml-server [1.9.0](https://github.com/allegroai/clearml-server/releases/tag/v1.9.0) is now out with [ClearML Reports](https://clear.ml/docs/latest/docs/webapp/webapp_reports).  You can create and share rich MarkDown documents that support embeddable online content (e.g. plots and debug samples from individual experiments or experiment comparisons)

**Comment by PierreSnell** [comment]
Hi, @pollfly thanks for the news it's really a wonderful feature! :D 

Would you know if there is a way to keep the report updated with the latest run for example? Or the one that has a `report` tag? (So I can show the management team the latest / best / up-to-date result instead of manually changing the markdown ?)

Thanks again for all your hard work! 
Have a great day.

**Comment by ainoam** [comment]
@PierreSnell Indeed there is:
You should edit the embed code so that instead of specifying a specific experiment you specify the criteria for the experiment you want to show e.g. for an embed code like the below that gets the 'training' scalar plot for a specific experiment 

`<iframe src="https://app.allegro-master.hosted.allegro.ai/widgets/?type=scalar&tasks=<task_id>&metrics=training" name="f068b7cd-cb8c-4508-9a28-3b8f044a7d96"  width="100%" height="400"></iframe>`

One would instead replace `tasks=...` with the criteria to match the tasks.
In our case, to get the latest run in your project use `page=0&page_size=1&project=<project_id>&order_by[]=-last_update`.
To get the experiment which has the `report` tag use `page=0&page_size=1&project=<project_id>&tags[]=__$or,report`.

**Comment by PierreSnell** [comment]
Hello @ainoam , 

Thanks a lot for the answer it's exactly what I needed. 
I guess the documentation will be updated soon. 

For me, we can close this issue as there are all the features I needed but you can keep it open if you need. 

Have a great day.
