### ISSUE TITLE
How to run my experiment in trains-agent if my code is not in Git and depends on several script files

### ISSUE THREAD

**Issue by columbo123** [allegroai/clearml#86]
I have created trains server and using trains agent to run code with changed hyper parameters. The original code which I ran from vscode worked fine. But whenever I run code from the trains UI with changed hyperparameter I get import error as my original script is at some other location. I have tried changing directory from code, and the script path and working directory option available in the UI. 
Anyone else facing the same issue and have solution?
Thanks in advance

**Comment by majdzr** [comment]
Hey @columbo123 , I faced the same. The cloned experiment code (not in a docker mode, similar to  #67 ) could not locate a local directory containing the data. Unfortunately, I still haven't found the time to investigate this further. Maybe this could give you a lead.

**Comment by columbo123** [comment]
I have sort of solved it but I don't think it can be a permanent solution
sys.path.insert(0,path_to_your_codes)
This solves the issue but I have to explicitly write this path for every code. 
If you are aware is there anyway we can bypass the process of new environment creation every time we run our code from trains UI and instead maybe we can use the current environment or a specific environment.

**Comment by bmartinn** [comment]
Hi @columbo123 ,

Just to make sure I understand your specific scenario:

1. Is your code part of a git repository, or are you using a single script file which is not part of a git repository?
2. Are the import errors for script files that reside next to the script you're running, or are they for script files inside folders that reside next to the script you're running? Can explain where your script file is located compared to the script files you're importing?
3. Are these imported script files part of any git repository, or just files you keep on your hard drive?
4. I assume you're running a trains-agent on the same machine in which you've run your code using vscode?

**Comment by columbo123** [comment]
1. No it is not part of any git repository, I have copy of code in my system. 
2. I have all my files which I have imported and the script I am running in same folder on my hard drive. But, trains seems to make a new copy of my script in its own environment. 
3.  These files are just in my repository. Btw can I run trains from one git repository as well?
4. Yes trains agent and server is running from same machine, the machine in which I am running my vscode script.
Thanks for the reply

**Comment by bmartinn** [comment]
A bit of background on *trains-agent*:
The goal of *trains-agent* is to run your code on any machine, including setting the environment for it (in virtual environment or inside a docker).
 *trains-agent* supports two modes of operation, when it comes to your code:
1) Single script file (or Jupyter notebook, that *trains* automatically stores as python script)
2) Git repository, including reference to a specific git commit, plus storing any uncommitted changes.

If you have a simple script or working inside a Jupyter Notebook, then option (1) is the straight forward approach. Basically creating an experiment with *trains* while running without any `.git` in the project will do exactly that, it will store the code as "Uncommitted Changes" without any reference to a git repository (because there wasn't)

If your code is more complex and you have a few python files and modules, then we believe the best approach is to add them to a git repository. And since you are here, GitHub hosts those git repositories for free :)
Just add all the files you need and commit them.
Once that's done *trains* will store on the experiment itself any uncommitted changes to the code (that said, I do recommend committing your code from time to time, you know backup and stuff...)

The *trains-agent* will pull the experiment and will do one of the following:
1) If no git repository is referenced by the experiment, it will just take the code from "Uncommitted Changes" in the "Execution" section and run that as python script
2) If there is a git repository, it will clone the git repository (to the exact same commit you were working on, when you first executed the original experiment), then it will apply any uncommitted changes, and execute the script from within the newly cloned repository.

Does that shine some light on the mechanics of *trains*/*trains-agent* ?

**Comment by columbo123** [comment]
Yah it shed the light, I will try to use the git feature. Thanks for the quick replies. Looking forward to contribute in this great project.

**Comment by columbo123** [comment]
Can I use git if my repository is private. I am using gitlab and my repository is private. When I run code from UI using trains agent it gives error.

**Comment by columbo123** [comment]
Hey, I am facing one more issue can you tell how to change port number of api server. I have changed it from docker-compose.yml and binded my local port to the updated port number. But still the requests are going through port number 8008.
Regards

**Comment by bmartinn** [comment]
*trains-server* supports two setup configuration:
- Port based - API/Web/Storage services are executed on the same domain/ip with different ports 8008/8080/8081
- Sub-domain setup - where the services are executed on different subdomains all on http/s port: api.aaa.example.com, app.aaa.example.com, files.aaa.example.dom (more details on the [FAQ](https://github.com/allegroai/trains-server/blob/master/docs/faq.md#configuration))

So answering your question, there is currently no way to tell the Web client to access the API server on a different port, so it is either sticking with 8008 , or setting a subdomain...

**Comment by omricarmi** [comment]
@bmartinn if I have projectA in folder located "/home/projectA/" and it depend on data located on "/home/data" how can it be handled?

**Comment by bmartinn** [comment]
Hi @omricarmi ,
First of all, I would strongly recommend having all your scripts stored in a git repo :)
That said, if you are running *trains-agent* in docker-mode, you can add extra docker arguments to both mount the data/script folder and point the os environment PYTHONPATH to them:

In your `~/trains.comf` configure the [agent.extra_docker_arguments](https://github.com/allegroai/trains-agent/blob/699d13bbb34649c7e5337b4187cda59b7fa6fd33/docs/trains.conf#L98), at the beginning of the file you can simply add:
```
agent.extra_docker_arguments = ["-v", "/home/projectA/:/home/projectA/", "-v", "/home/data/:/home/data/", "-e", "PYTHONPATH=/home/data/"]
```

These arguments will always be added to your docker execution, on top of everything else you have in the "Base Docker Image" section on the specific experiment.

How does that sound?

**Comment by omricarmi** [comment]
Sounds great 👌

**Comment by omricarmi** [comment]
@bmartinn is it the best practice for local dataset?

**Comment by bmartinn** [comment]
@omricarmi I missed this one :(

> is it the best practice for local dataset

I guess you have three options:
1. Have the dataset on a shared drive, pre-mounted on all the agent machines / dockers
2. Upload the dataset to S3 (or any other storage solution), then use the `StorageManager` to download the data 
(Since caching is supported, uploading the entire dataset as a zip, then the `StorageManager` can return the unzippped cached folder for you code to work with)
3. Similar to (2) only have it as an artifact on a dedicated task (let's call it 'dataset_upload_task')
Then use `Task.get_task(task_id='dataset_upload_task_id').artifacts['dataset'].get_local_copy()`

What do you think?
