### ISSUE TITLE
Export experiments to csv

### ISSUE THREAD

**Issue by PierreSnell** [allegroai/clearml#882]
## Proposal Summary
When looking at all experiments (or filtered), export all to csv. 

Report table (in clearML)
```
------------------------
| Name | Key_1 | Key_2 |
------------------------
| Hey  | Val_1 | Val_2 | 
------------------------      
``` 
To (as csv)
```
Name, Key_1, Key_2
Hey, Val_1, Val_2
```

## Motivation
Help to present result to non technical / business / persons that don't have access to clearML

**Comment by ainoam** [comment]
We were thinking the same thing @PierreSnell :)
It should be coming soon - We'll update here when available.

**Comment by pollfly** [comment]
Hey @PierreSnell! [clearml-server 1.12.0](https://github.com/allegroai/clearml-server/releases/tag/v1.12.0) is now out, and  supports exporting UI object table data in CSV format.

**Comment by PierreSnell** [comment]
Hello @pollfly, 

Thanks for the update ! It indeed works really well, and we're using it often :) 

However, I'm sorry for the confusion but I was thinking about the project table (as in the screenshot bellow) that would need to be exported to csv.

![image](https://github.com/allegroai/clearml/assets/116119917/a508358a-aef9-40b9-81b6-fe1dd2cac2a1)

That would give me (in this example) 

 ```
TYPE, NAME, TAGS, STATUS, USER, STARTED, UPDATED, ITERATION, PARENT, Acc, #Train, #Test
Train, Bisque_robert, Aborted, Pierre, date, date, 0, , 0.75, 84, 36, 24, 24
.....
```

**Comment by pollfly** [comment]
Hey @PierreSnell,  

Can you clarify what is missing? Since [clearml-server 1.12.0](https://github.com/allegroai/clearml-server/releases/tag/v1.12.0), every one of the tables in the UI (experiment, model, pipeline, dataset, etc.) should have a "Download table as CSV" button on the top right (see image), which creates a csv file formatted like your example 
![image](https://github.com/allegroai/clearml/assets/75068813/5e76e8d6-a277-42e8-9c60-2f8420c39cd1)

**Comment by PierreSnell** [comment]
Hello @pollfly, 

That's one is on me... I'm sorry I got a tiny earliest version. Upgrading I can confirm that everything works like a charm. 

Thanks for the fast feedback and this amazing tool. 
Have a nice week.
